version: "3.3"
services:
    wordpress:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8888:80"
        depends_on:
            - db
        env_file: .env
        volumes:
            - ./src:/var/www/html/wp-content/plugins/static-post-type
            - ./devenv/languages:/var/www/html/wp-content/languages
            # - ./devenv/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - for-testing:/tmp
    db:
        image: mysql:5.7
        env_file: .env
        volumes:
            - db-data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        env_file: .env
        links:
            - db
        ports:
             - 8080:80
        volumes:
             - ./tmp/phpmyadmin-sessions:/sessions

volumes:
    db-data:
        driver: local
    for-testing:
        driver: local
    language-files:
        driver: local
