version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
            name: docker-compose up
            command: docker-compose up -d --build

      - run:
            name: install wordpress
            command: wp core install --url=localhost:8888 --title=StaticPostTypeDev --admin_user=admin@example.com --admin_password=pass --admin_email=admin@example.com

      - cache-restore:
          key: repo-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      - cache-save:
          key: repo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run: bundle exec ruby test/home.rb